include: package:pedantic_mono/analysis_options.yaml

linter:
  rules:

analyzer:
  exclude:
    - lib/**/*.gql.dart
    - lib/**/*.gql.g.dart
    - lib/**/*.freezed.dart

  errors:
    argument_type_not_assignable: warning
